In [4]:
#fazendo a primeiro requisição na b3
import requests
from bs4 import BeautifulSoup

url = "https://sistemaswebb3-listados.b3.com.br/indexPage/day/IBOV?language=pt-BR"
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)

print(f"Status: {response.status_code}")
print(f"Tamanho do HTML: {len(response.text)} caracteres")

Status: 200
Tamanho do HTML: 2594 caracteres

In [5]:
#testando encoding
import requests
from bs4 import BeautifulSoup

url = "https://sistemaswebb3-listados.b3.com.br/indexPage/day/IBOV?language=pt-BR"
headers = {"User-Agent": "Mozilla/5.0"}

response.encoding = "utf-8" 
soup = BeautifulSoup(response.text, "html.parser")
print(soup.title.text)

Índices

In [6]:
# Transformar o HTML em objeto navegável
soup = BeautifulSoup(response.text, "html.parser")

# Ver o título da página
print(soup.title.text)

# Ver os primeiros 500 caracteres do HTML
print(response.text[:500])

Índices
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Índices</title>
  <base href="/indexPage/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="/indexPage/ruxitagentjs_ICANVfgqru_10333260303165926.js" data-dtconfig="rid=RID_89656357|rpid=1268034328|domain=b3.com.br|reportUrl=/indexPage/rb_ea8d7b8f-040c-423b-b726-54310cab2c40|app=fd69ce40c52bd20e|cuc=kju5m9kg|owasp=1|mel=100000|featureHash=ICANVfgqru|dpvc=1

In [7]:
#Empresas ESG

url_ise = "https://www.b3.com.br/pt_br/market-data-e-indices/indices/indices-de-sustentabilidade/indice-de-sustentabilidade-empresarial-ise-b3.htm"

response = requests.get(url_ise, headers=headers)
print(f"Status: {response.status_code}")

Status: 200

In [8]:
url_api = "https://sistemaswebb3-listados.b3.com.br/indexProxy/indexCall/GetPortfolioDay/eyJsYW5ndWFnZSI6InB0LWJSIiwicGFnZU51bWJlciI6MSwicGFnZVNpemUiOjIwLCJpbmRleCI6IklTRSIsInNlZ21lbnQiOiIxIn0="

response = requests.get(url_api, headers=headers)
dados = response.json()
print(dados)

{'page': {'pageNumber': 1, 'pageSize': 20, 'totalRecords': None, 'totalPages': None}, 'header': None, 'results': None}

In [9]:
import base64
import json

# Decodificar o token atual
token = "eyJsYW5ndWFnZSI6InB0LWJSIiwicGFnZU51bWJlciI6MSwicGFnZVNpemUiOjIwLCJpbmRleCI6IklTRSIsInNlZ21lbnQiOiIxIn0="
decoded = base64.b64decode(token).decode("utf-8")
print(decoded)

{"language":"pt-bR","pageNumber":1,"pageSize":20,"index":"ISE","segment":"1"}

In [10]:
import pandas as pd
import requests

# Carteira ISE vigente em CSV direto
url_ise_csv = "https://sistemaswebb3-listados.b3.com.br/indexProxy/indexCall/GetDownloadPortfolioDay/eyJsYW5ndWFnZSI6InB0LWJSIiwiaW5kZXgiOiJJU0UiLCJzZWdtZW50IjoiMSJ9"

response = requests.get(url_ise_csv, headers=headers)
print(f"Status: {response.status_code}")
print(f"Tipo de conteúdo: {response.headers.get('content-type')}")
print(response.text[:500])

Status: 200
Tipo de conteúdo: text/plain; charset=utf-8

In [34]:
from io import StringIO
import pandas as pd

df_ise = pd.read_csv(StringIO(response.text), sep=";", encoding="utf-8", skipfooter=2, engine="python")
print(df_ise.shape)
print(df_ise.columns.tolist())
df_ise.head()

(4, 1)
['<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">']

  <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
0                                       <html><head>
1                       <title>404 Not Found</title>
2                                      </head><body>
3                                 <h1>Not Found</h1>

In [13]:
import requests
import pandas as pd
from io import StringIO

headers = {"User-Agent": "Mozilla/5.0"}

# Refazer a requisição
url_ise_csv = "https://sistemaswebb3-listados.b3.com.br/indexProxy/indexCall/GetDownloadPortfolioDay/eyJsYW5ndWFnZSI6InB0LWJSIiwiaW5kZXgiOiJJU0UiLCJzZWdtZW50IjoiMSJ9"

response = requests.get(url_ise_csv, headers=headers)
print(f"Status: {response.status_code}")
print(f"Tamanho: {len(response.text)} caracteres")
print(f"Primeiros 300 caracteres:")
print(response.text[:300])

Status: 200
Tamanho: 0 caracteres
Primeiros 300 caracteres:

In [14]:
import requests
import pandas as pd
from io import StringIO

headers = {"User-Agent": "Mozilla/5.0"}

# Endpoint alternativo — lista de empresas ISE
url = "https://sistemaswebb3-listados.b3.com.br/indexProxy/indexCall/GetPortfolioDay/eyJsYW5ndWFnZSI6InB0LWJSIiwicGFnZU51bWJlciI6MSwicGFnZVNpemUiOjEwMCwiaW5kZXgiOiJJU0UiLCJzZWdtZW50IjoiMSJ9"

response = requests.get(url, headers=headers)
print(f"Status: {response.status_code}")
dados = response.json()
print(dados.keys())
print(dados)

Status: 200
dict_keys(['page', 'header', 'results'])
{'page': {'pageNumber': 1, 'pageSize': 100, 'totalRecords': None, 'totalPages': None}, 'header': None, 'results': None}

In [15]:
import requests
import pandas as pd

headers = {"User-Agent": "Mozilla/5.0"}

# Autos de infração IBAMA — API aberta
url_ibama = "https://dadosabertos.ibama.gov.br/dados/SISNAMA/auto_infracao/auto_infracao.csv"

response = requests.get(url_ibama, headers=headers, timeout=30)
print(f"Status: {response.status_code}")
print(f"Tamanho: {len(response.content)} bytes")

Status: 404
Tamanho: 196 bytes

In [24]:
import pandas as pd

# alterado de utf-8 para latin
df_ise = pd.read_csv(
    r"C:\carbontrack-br\data\raw\ise_carteira.csv",
    sep=";",
    encoding="latin1",
    skipfooter=2,
    engine="python"
)

print(df_ise.shape)
print(df_ise.columns.tolist())
df_ise.head()

(75, 1)
['ISEE - Carteira do Dia 22/04/26']

                                                     ISEE - Carteira do Dia 22/04/26
Código Ação      Tipo       Qtde. Teórica Part. (%)
TTEN3  3TENTOS   ON      NM 197.829.830   0,316                                  NaN
AERI3  AERIS     ON      NM 50.488.135    0,015                                  NaN
ALOS3  ALLOS     ON      NM 667.559.139   2,230                                  NaN
ABEV3  AMBEV S/A ON         1.341.987.445 2,049                                  NaN
ASAI3  ASSAI     ON      NM 2.331.549.589 2,221                                  NaN

In [18]:
# Portal de dados abertos do IBAMA atualizado
url_ibama = "https://dadosabertos.ibama.gov.br/dados/SISNAMA/auto_infracao/auto_infracao_v2.csv"

response = requests.get(url_ibama, headers=headers, timeout=30)
print(f"Status: {response.status_code}")
print(f"Tamanho: {len(response.content)} bytes")

Status: 404
Tamanho: 196 bytes

In [28]:
df_ise = pd.read_csv(
    r"C:\carbontrack-br\data\raw\ise_carteira.csv",
    sep=";",
    encoding="latin1",
    skiprows=1,
    skipfooter=2,
    engine="python",
    names=["codigo", "acao", "tipo", "qtde_teorica", "participacao_pct", "vazio"],
    header=0
)

# Remover coluna vazia
df_ise = df_ise.drop(columns=["vazio"])

print(df_ise.shape)
print(df_ise.columns.tolist())
df_ise.head(10)

(75, 5)
['codigo', 'acao', 'tipo', 'qtde_teorica', 'participacao_pct']

  codigo          acao        tipo   qtde_teorica participacao_pct
0  TTEN3       3TENTOS  ON      NM    197.829.830            0,316
1  AERI3         AERIS  ON      NM     50.488.135            0,015
2  ALOS3         ALLOS  ON      NM    667.559.139            2,230
3  ABEV3     AMBEV S/A          ON  1.341.987.445            2,049
4  ASAI3         ASSAI  ON      NM  2.331.549.589            2,221
5  AURE3         AUREN  ON      NM    554.475.346            0,808
6  AXIA3  AXIA ENERGIA  ON      N1    386.196.964            2,462
7  AXIA7  AXIA ENERGIA  PNC     N1    101.507.194            0,620
8  AZZA3    AZZAS 2154  ON      NM    230.676.721            0,503
9  B3SA3            B3  ON      NM  1.618.996.161            3,108

In [29]:
# Salvar ISE limpo
df_ise.to_csv(
    r"C:\carbontrack-br\data\processed\ise_limpo.csv",
    index=False,
    sep=";",
    encoding="utf-8-sig"
)
print("ISE salvo!")

# Carregar CVM que você já limpou
df_cvm = pd.read_csv(
    r"C:\carbontrack-br\data\processed\empresas_mg_esg.csv",
    sep=";",
    encoding="utf-8-sig"
)

# Cruzamento — empresas que estão nos dois datasets
# ISE usa código de ação (PETR4), CVM usa CNPJ
# Vamos cruzar pelo nome da empresa
df_ise["acao_limpa"] = df_ise["acao"].str.strip().str.upper()
df_cvm["nome_limpo"] = df_cvm["DENOM_SOCIAL"].str.strip().str.upper()

# Ver as empresas ISE de MG
empresas_ise = df_ise["acao_limpa"].tolist()
print(f"\nEmpresas no ISE: {len(empresas_ise)}")
print(empresas_ise)

ISE salvo!

Empresas no ISE: 75
['3TENTOS', 'AERIS', 'ALLOS', 'AMBEV S/A', 'ASSAI', 'AUREN', 'AXIA ENERGIA', 'AXIA ENERGIA', 'AZZAS 2154', 'B3', 'BRADESCO', 'BRASIL', 'BRASKEM', 'BTGP BANCO', 'CAMIL', 'CASAS BAHIA', 'CBA', 'CEA MODAS', 'CEMIG', 'COGNA ON', 'COPASA', 'COPEL', 'COSAN', 'CPFL ENERGIA', 'CYRELA REALT', 'CYRELA REALT', 'DEXCO', 'ECORODOVIAS', 'ENEVA', 'ENGIE BRASIL', 'EQUATORIAL', 'FLEURY', 'GAFISA', 'HIDROVIAS', 'HYPERA', 'IGUATEMI S.A', 'IOCHP-MAXION', 'IRANI', 'ISA ENERGIA', 'ITAUSA', 'ITAUUNIBANCO', 'JSL', 'KLABIN S/A', 'LOJAS RENNER', 'M.DIASBRANCO', 'MAGAZ LUIZA', 'MARFRIG', 'MINERVA', 'MITRE REALTY', 'MOTIVA SA', 'MOVIDA', 'MRV', 'NATURA', 'OCEANPACT', 'ODONTOPREV', 'PORTO SEGURO', 'PORTOBELLO', 'QUERO-QUERO', 'RAIADROGASIL', 'REDE D OR', 'RIACHUELO', 'RUMO S.A.', 'SABESP', 'SANEPAR', 'SANTANDER BR', 'SIMPAR', 'SLC AGRICOLA', 'TELEF BRASIL', 'TIM', 'ULTRAPAR', 'USIMINAS', 'VAMOS', 'VIBRA', 'WEG', 'YDUQS PART']

In [30]:
# Carregar o cadastro CVM completo (não só MG)
df_cvm_completo = pd.read_csv(
    r"C:\carbontrack-br\data\raw\cad_cia_aberta.csv",
    sep=";",
    encoding="latin1"
)

# Filtrar só ativas
df_cvm_ativas = df_cvm_completo[df_cvm_completo["SIT"] == "ATIVO"].copy()
df_cvm_ativas["nome_limpo"] = df_cvm_ativas["DENOM_SOCIAL"].str.strip().str.upper()

# Cruzamento por nome — buscar cada empresa ISE na CVM
matches = []

for _, empresa in df_ise.iterrows():
    nome_ise = empresa["acao_limpa"]
    
    # Buscar na CVM empresas que contenham o nome ISE
    encontradas = df_cvm_ativas[df_cvm_ativas["nome_limpo"].str.contains(nome_ise, na=False)]
    
    if len(encontradas) > 0:
        for _, cvm in encontradas.iterrows():
            matches.append({
                "codigo_ise": empresa["codigo"],
                "nome_ise": nome_ise,
                "nome_cvm": cvm["DENOM_SOCIAL"],
                "cnpj": cvm["CNPJ_CIA"],
                "setor": cvm["SETOR_ATIV"],
                "uf": cvm["UF"],
                "participacao_pct": empresa["participacao_pct"]
            })

df_cruzado = pd.DataFrame(matches)
print(f"Empresas ISE encontradas na CVM: {df_cruzado['codigo_ise'].nunique()}")
print(f"Total de registros: {len(df_cruzado)}")
df_cruzado.head(15)

Empresas ISE encontradas na CVM: 51
Total de registros: 164

,codigo_ise,nome_ise,nome_cvm,cnpj,setor,uf,participacao_pct
0,AERI3,AERIS,AERIS IND. E COM. DE EQUIP. PARA GER. DE ENG. ...,12.528.708/0001-07,"Máquinas, Equipamentos, Veículos e Peças",CE,"0,015"
1,AERI3,AERIS,AERIS IND. E COM. DE EQUIP. PARA GER. DE ENG. ...,12.528.708/0001-07,"Máquinas, Equipamentos, Veículos e Peças",CE,"0,015"
2,ALOS3,ALLOS,ALLOS S.A.,05.878.397/0001-32,Emp. Adm. Part. - Comércio (Atacado e Varejo),RJ,"2,230"
3,ALOS3,ALLOS,ALLOS S.A.,05.878.397/0001-32,Emp. Adm. Part. - Comércio (Atacado e Varejo),RJ,"2,230"
4,AURE3,AUREN,AUREN ENERGIA S.A,28.594.234/0001-23,Energia Elétrica,SP,"0,808"
5,AURE3,AUREN,AUREN ENERGIA S.A,28.594.234/0001-23,Energia Elétrica,SP,"0,808"
6,AURE3,AUREN,AUREN OPERAÇÕES S.A.,00.194.724/0001-13,Emp. Adm. Part. - Energia Elétrica,SP,"0,808"
7,AURE3,AUREN,AUREN PARTICIPAÇÕES S.A.,37.663.076/0001-07,Energia Elétrica,SP,"0,808"
8,AXIA3,AXIA ENERGIA,AXIA ENERGIA NORDESTE S.A.,33.541.368/0001-16,Energia Elétrica,PE,"2,462"
9,AXIA3,AXIA ENERGIA,AXIA ENERGIA NORTE S.A.,00.357.038/0001-16,Energia Elétrica,DF,"2,462"
10,AXIA3,AXIA ENERGIA,AXIA ENERGIA SUL S.A.,02.016.507/0001-69,Energia Elétrica,SC,"2,462"
11,AXIA7,AXIA ENERGIA,AXIA ENERGIA NORDESTE S.A.,33.541.368/0001-16,Energia Elétrica,PE,"0,620"
12,AXIA7,AXIA ENERGIA,AXIA ENERGIA NORTE S.A.,00.357.038/0001-16,Energia Elétrica,DF,"0,620"
13,AXIA7,AXIA ENERGIA,AXIA ENERGIA SUL S.A.,02.016.507/0001-69,Energia Elétrica,SC,"0,620"
14,AZZA3,AZZAS 2154,AZZAS 2154 S.A.,16.590.234/0001-76,Têxtil e Vestuário,MG,"0,503"

In [31]:
# Ver as empresas de MG no cruzamento
df_ise_mg = df_cruzado[df_cruzado["uf"] == "MG"].copy()
print(f"Empresas ISE em MG: {len(df_ise_mg)}")
print(df_ise_mg[["codigo_ise", "nome_ise", "nome_cvm", "setor"]].to_string())

Empresas ISE em MG: 9
    codigo_ise    nome_ise                                  nome_cvm                                       setor
14       AZZA3  AZZAS 2154                           AZZAS 2154 S.A.                          Têxtil e Vestuário
25       BBAS3      BRASIL                 BANCO MERCANTIL BRASIL SA                                      Bancos
81       CMIG4       CEMIG                    CEMIG DISTRIBUIÇÃO S/A                            Energia Elétrica
82       CMIG4       CEMIG           CEMIG GERAÇÃO E TRANSMISSÃO S/A                            Energia Elétrica
83       CMIG4       CEMIG            CIA ENERG MINAS GERAIS - CEMIG                            Energia Elétrica
126      MRVE3         MRV        MRV ENGENHARIA E PARTICIPAÇÕES S/A  Construção Civil, Mat. Constr. e Decoração
139      TIMS3         TIM     BANCO MERCANTIL DE INVESTIMENTOS S.A.                                      Bancos
156      USIM5    USIMINAS  USINAS SID DE MINAS GERAIS S.A.-USIMINAS                     Metalurgia e Siderurgia
157      USIM5    USIMINAS  USINAS SID DE MINAS GERAIS S.A.-USIMINAS                     Metalurgia e Siderurgia

In [32]:
# Salvar cruzamento completo
df_cruzado.to_csv(
    r"C:\carbontrack-br\data\processed\ise_x_cvm.csv",
    index=False,
    sep=";",
    encoding="utf-8-sig"
)

# Salvar só MG
df_ise_mg.to_csv(
    r"C:\carbontrack-br\data\processed\ise_mg.csv",
    index=False,
    sep=";",
    encoding="utf-8-sig"
)

print("Arquivos salvos!")
print(f"\nResumo do CarbonTrack BR até agora:")
print(f"Empresas CVM ativas:         {len(df_cvm_ativas)}")
print(f"Empresas ISE (certificadas): {df_cruzado['codigo_ise'].nunique()}")
print(f"Empresas ISE em MG:          {len(df_ise_mg)}")

Arquivos salvos!

Resumo do CarbonTrack BR até agora:
Empresas CVM ativas:         767
Empresas ISE (certificadas): 51
Empresas ISE em MG:          9

In [33]:
# Salvar arquivos
df_cruzado.to_csv(
    r"C:\carbontrack-br\data\processed\ise_x_cvm.csv",
    index=False, sep=";", encoding="utf-8-sig"
)

df_ise_mg.to_csv(
    r"C:\carbontrack-br\data\processed\ise_mg.csv",
    index=False, sep=";", encoding="utf-8-sig"
)

print("Resumo do CarbonTrack BR:")
print(f"Empresas CVM ativas:              {len(df_cvm_ativas)}")
print(f"Empresas ISE certificadas:        {df_cruzado['codigo_ise'].nunique()}")
print(f"Empresas ISE em MG:               {df_ise_mg['codigo_ise'].nunique()}")
print(f"Destaques: CEMIG, USIMINAS, MRV")

Resumo do CarbonTrack BR:
Empresas CVM ativas:              767
Empresas ISE certificadas:        51
Empresas ISE em MG:               6
Destaques: CEMIG, USIMINAS, MRV