In [11]:
import pandas as pd

df = pd.read_csv("cad_cia_aberta.csv", sep=";", encoding="latin1")
df

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
0,08.773.135/0001-00,2W ECOBANK S.A. - EM RECUPERAÇÃO JUDICIAL,2W ECOBANK S.A.,2020-10-29,2007-03-23,NaN,NaN,ATIVO,2020-10-29,25224,...,NaN,NaN,4711130.0,11.0,39579400.0,NaN,NaN,juridico@2wecobank.com.br,10.830.108/0001-65,GRANT THORNTON AUDITORES INDEPENDENTES LTDA.
1,11.396.633/0001-87,3A COMPANHIA SECURITIZADORA,TRIPLO A COMPANHIA SECURITIZADORA,2010-03-08,2009-11-03,2015-12-18,Cancelamento Voluntário - IN CVM 480/09,CANCELADA,2015-12-18,21954,...,RJ,NaN,20020000.0,21.0,22338867.0,21.0,22338867.0,juridico@triploasec.com.br,60.525.706/0001-07,MOORE STEPHENS LIMA LUCCHESI AUDITORES INDEPEN...
2,01.547.749/0001-16,521 PARTICIPAÇOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,521 PARTICIPAÇÕES S/A,1997-07-11,1996-07-30,NaN,NaN,ATIVO,1997-07-11,16330,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02.878.522/0001-16,IRKO HIRASHIMA AUDITORES INDEPENDENTES LTDA.
3,01.851.771/0001-55,524 PARTICIPAÇOES SA,524 PARTICIPACOES SA,1997-05-30,1997-04-02,NaN,NaN,ATIVO,1997-05-30,16284,...,RJ,NaN,20020010.0,21.0,38043700.0,NaN,NaN,gar@opportunity.com.br,10.830.108/0001-65,GRANT THORNTON AUDITORES INDEPENDENTES LTDA.
4,01.919.008/0001-19,525 PARTICIPAÇOES SA,525 PARTICIPACOES SA,1997-07-16,1997-04-02,2006-05-30,ELISÃO POR INCORPORAÇÃO,CANCELADA,2006-05-30,16349,...,RJ,NaN,22290160.0,21.0,21967200.0,21.0,21967201.0,kevin@mattosfilho.com.br,11.245.719/0001-09,DIRECTA AUDITORES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2666,13.574.594/0001-96,ZAMP S.A.,ZAMP S.A.,2017-12-14,2011-04-06,NaN,NaN,ATIVO,2017-12-14,24317,...,NaN,NaN,6455020.0,11.0,23970320.0,NaN,NaN,ri@burgerking.com.br,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2667,71.320.931/0001-15,ZANINI SA EQUIPS PESADOS,ZANINI,1971-07-05,NaN,1997-01-27,ATENDIMENTO AS NORMAS DA INSTR CVM 03/78,CANCELADA,1997-01-27,11835,...,SP,NaN,1013000.0,11.0,6424066.0,11.0,NaN,NaN,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2668,24.744.012/0001-99,ZH OPERAÇÕES S/A,ZH OPERAÇÕES S/A,2016-09-16,2016-04-15,2017-08-07,Cancelamento de ofício - IN CVM 480/09,CANCELADA,2017-08-07,24007,...,SP,NaN,4609005.0,11.0,50548989.0,NaN,NaN,renno@setaatacadista.com.br,00.115.909/0001-95,MS AUDITORES INDEPENDENTES S/C
2669,92.749.217/0001-17,ZIVI SA CUTELARIA,ZIVI S/A,1968-11-01,1931-01-01,2003-12-29,ELISÃO POR INCORPORAÇÃO,CANCELADA,2003-12-29,11843,...,RS,NaN,91030530.0,51.0,33585109.0,51.0,33585176.0,michael.ceitlin@gem.ind.br,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2670,74.533.787/0001-93,ZOGBI LEASING S/A ARRENDAMENTO MERCANTIL,ZOGBI LEASING,1997-09-18,1993-06-18,2004-12-23,ATENDIMENTO AS NORMAS DA INSTRUÇÃO CVM Nº 361/02,CANCELADA,2004-12-23,16462,...,NaN,NaN,6029900.0,11.0,36814011.0,11.0,36844630.0,4000.isola@bradesco.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.

In [8]:
# Quantas linhas e colunas
df.shape

(2671, 47)

In [18]:
# Nomes das colunas
df.columns.tolist()

['CNPJ_CIA',
 'DENOM_SOCIAL',
 'DENOM_COMERC',
 'DT_REG',
 'DT_CONST',
 'DT_CANCEL',
 'MOTIVO_CANCEL',
 'SIT',
 'DT_INI_SIT',
 'CD_CVM',
 'SETOR_ATIV',
 'TP_MERC',
 'CATEG_REG',
 'DT_INI_CATEG',
 'SIT_EMISSOR',
 'DT_INI_SIT_EMISSOR',
 'CONTROLE_ACIONARIO',
 'TP_ENDER',
 'LOGRADOURO',
 'COMPL',
 'BAIRRO',
 'MUN',
 'UF',
 'PAIS',
 'CEP',
 'DDD_TEL',
 'TEL',
 'DDD_FAX',
 'FAX',
 'EMAIL',
 'TP_RESP',
 'RESP',
 'DT_INI_RESP',
 'LOGRADOURO_RESP',
 'COMPL_RESP',
 'BAIRRO_RESP',
 'MUN_RESP',
 'UF_RESP',
 'PAIS_RESP',
 'CEP_RESP',
 'DDD_TEL_RESP',
 'TEL_RESP',
 'DDD_FAX_RESP',
 'FAX_RESP',
 'EMAIL_RESP',
 'CNPJ_AUDITOR',
 'AUDITOR']

CNPJ_CIA               object
DENOM_SOCIAL           object
DENOM_COMERC           object
DT_REG                 object
DT_CONST               object
DT_CANCEL              object
MOTIVO_CANCEL          object
SIT                    object
DT_INI_SIT             object
CD_CVM                  int64
SETOR_ATIV             object
TP_MERC                object
CATEG_REG              object
DT_INI_CATEG           object
SIT_EMISSOR            object
DT_INI_SIT_EMISSOR     object
CONTROLE_ACIONARIO     object
TP_ENDER               object
LOGRADOURO             object
COMPL                  object
BAIRRO                 object
MUN                    object
UF                     object
PAIS                   object
CEP                   float64
DDD_TEL               float64
TEL                   float64
DDD_FAX               float64
FAX                   float64
EMAIL                  object
TP_RESP                object
RESP                   object
DT_INI_RESP            object
LOGRADOURO_RESP        object
COMPL_RESP             object
BAIRRO_RESP            object
MUN_RESP               object
UF_RESP                object
PAIS_RESP              object
CEP_RESP              float64
DDD_TEL_RESP          float64
TEL_RESP              float64
DDD_FAX_RESP          float64
FAX_RESP              float64
EMAIL_RESP             object
CNPJ_AUDITOR           object
AUDITOR                object
dtype: object

In [7]:
# Primeiras linhas
df.head()

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
0,08.773.135/0001-00,2W ECOBANK S.A. - EM RECUPERAÇÃO JUDICIAL,2W ECOBANK S.A.,2020-10-29,2007-03-23,NaN,NaN,ATIVO,2020-10-29,25224,...,NaN,NaN,4711130.0,11.0,39579400.0,NaN,NaN,juridico@2wecobank.com.br,10.830.108/0001-65,GRANT THORNTON AUDITORES INDEPENDENTES LTDA.
1,11.396.633/0001-87,3A COMPANHIA SECURITIZADORA,TRIPLO A COMPANHIA SECURITIZADORA,2010-03-08,2009-11-03,2015-12-18,Cancelamento Voluntário - IN CVM 480/09,CANCELADA,2015-12-18,21954,...,RJ,NaN,20020000.0,21.0,22338867.0,21.0,22338867.0,juridico@triploasec.com.br,60.525.706/0001-07,MOORE STEPHENS LIMA LUCCHESI AUDITORES INDEPEN...
2,01.547.749/0001-16,521 PARTICIPAÇOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,521 PARTICIPAÇÕES S/A,1997-07-11,1996-07-30,NaN,NaN,ATIVO,1997-07-11,16330,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02.878.522/0001-16,IRKO HIRASHIMA AUDITORES INDEPENDENTES LTDA.
3,01.851.771/0001-55,524 PARTICIPAÇOES SA,524 PARTICIPACOES SA,1997-05-30,1997-04-02,NaN,NaN,ATIVO,1997-05-30,16284,...,RJ,NaN,20020010.0,21.0,38043700.0,NaN,NaN,gar@opportunity.com.br,10.830.108/0001-65,GRANT THORNTON AUDITORES INDEPENDENTES LTDA.
4,01.919.008/0001-19,525 PARTICIPAÇOES SA,525 PARTICIPACOES SA,1997-07-16,1997-04-02,2006-05-30,ELISÃO POR INCORPORAÇÃO,CANCELADA,2006-05-30,16349,...,RJ,NaN,22290160.0,21.0,21967200.0,21.0,21967201.0,kevin@mattosfilho.com.br,11.245.719/0001-09,DIRECTA AUDITORES

In [9]:
# Quantos valores nulos por coluna
df.isnull().sum()

CNPJ_CIA                 0
DENOM_SOCIAL             0
DENOM_COMERC            95
DT_REG                   0
DT_CONST               929
DT_CANCEL              770
MOTIVO_CANCEL          772
SIT                      0
DT_INI_SIT               0
CD_CVM                   0
SETOR_ATIV               6
TP_MERC               1902
CATEG_REG             1239
DT_INI_CATEG          1239
SIT_EMISSOR           1330
DT_INI_SIT_EMISSOR    1330
CONTROLE_ACIONARIO       2
TP_ENDER                 1
LOGRADOURO               1
COMPL                 1208
BAIRRO                 645
MUN                      1
UF                       1
PAIS                   102
CEP                      2
DDD_TEL                 26
TEL                     26
DDD_FAX                868
FAX                    855
EMAIL                  994
TP_RESP                 71
RESP                    71
DT_INI_RESP             71
LOGRADOURO_RESP         74
COMPL_RESP            1280
BAIRRO_RESP            770
MUN_RESP                83
UF_RESP                476
PAIS_RESP             2649
CEP_RESP                73
DDD_TEL_RESP            75
TEL_RESP                76
DDD_FAX_RESP           898
FAX_RESP              1437
EMAIL_RESP             889
CNPJ_AUDITOR           100
AUDITOR                100
dtype: int64

In [15]:
colunas_uteis = [
    "CNPJ_CIA",
    "DENOM_SOCIAL",
    "DENOM_COMERC",
    "DT_REG",
    "SIT",
    "SETOR_ATIV",
    "CONTROLE_ACIONARIO",
    "UF",
    "PAIS",
    "EMAIL",
    "AUDITOR"
]

df_limpo = df[colunas_uteis]
df_limpo.head()

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,SIT,SETOR_ATIV,CONTROLE_ACIONARIO,UF,PAIS,EMAIL,AUDITOR
0,08.773.135/0001-00,2W ECOBANK S.A. - EM RECUPERAÇÃO JUDICIAL,2W ECOBANK S.A.,2020-10-29,ATIVO,Energia Elétrica,PRIVADO,SP,BRASIL,ri@2wecobank.com.br,GRANT THORNTON AUDITORES INDEPENDENTES LTDA.
1,11.396.633/0001-87,3A COMPANHIA SECURITIZADORA,TRIPLO A COMPANHIA SECURITIZADORA,2010-03-08,CANCELADA,Securitização de Recebíveis,PRIVADO,RJ,BRASIL,dri@3asec.com.br,MOORE STEPHENS LIMA LUCCHESI AUDITORES INDEPEN...
2,01.547.749/0001-16,521 PARTICIPAÇOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,521 PARTICIPAÇÕES S/A,1997-07-11,ATIVO,Emp. Adm. Part. - Energia Elétrica,PRIVADO,RJ,BRASIL,eximia@eximiacapital.com,IRKO HIRASHIMA AUDITORES INDEPENDENTES LTDA.
3,01.851.771/0001-55,524 PARTICIPAÇOES SA,524 PARTICIPACOES SA,1997-05-30,ATIVO,Emp. Adm. Part. - Sem Setor Principal,PRIVADO,RJ,BRASIL,gar@opportunity.com.br,GRANT THORNTON AUDITORES INDEPENDENTES LTDA.
4,01.919.008/0001-19,525 PARTICIPAÇOES SA,525 PARTICIPACOES SA,1997-07-16,CANCELADA,Emp. Adm. Part. - Sem Setor Principal,PRIVADO HOLDING,RJ,BRASIL,NaN,DIRECTA AUDITORES

In [19]:
df_limpo["SIT"].value_counts()

SIT
CANCELADA                    1901
ATIVO                         767
SUSPENSO(A) - DECISÃO ADM       3
Name: count, dtype: int64

In [20]:
# Filtrar só as ativas
df_ativas = df_limpo[df_limpo["SIT"] == "ATIVO"]
print(f"Total de empresas ativas: {len(df_ativas)}")
df_ativas.head()

Total de empresas ativas: 767

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,SIT,SETOR_ATIV,CONTROLE_ACIONARIO,UF,PAIS,EMAIL,AUDITOR
0,08.773.135/0001-00,2W ECOBANK S.A. - EM RECUPERAÇÃO JUDICIAL,2W ECOBANK S.A.,2020-10-29,ATIVO,Energia Elétrica,PRIVADO,SP,BRASIL,ri@2wecobank.com.br,GRANT THORNTON AUDITORES INDEPENDENTES LTDA.
2,01.547.749/0001-16,521 PARTICIPAÇOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,521 PARTICIPAÇÕES S/A,1997-07-11,ATIVO,Emp. Adm. Part. - Energia Elétrica,PRIVADO,RJ,BRASIL,eximia@eximiacapital.com,IRKO HIRASHIMA AUDITORES INDEPENDENTES LTDA.
3,01.851.771/0001-55,524 PARTICIPAÇOES SA,524 PARTICIPACOES SA,1997-05-30,ATIVO,Emp. Adm. Part. - Sem Setor Principal,PRIVADO,RJ,BRASIL,gar@opportunity.com.br,GRANT THORNTON AUDITORES INDEPENDENTES LTDA.
13,07.636.657/0001-99,ACO VERDE DO BRASIL S.A,AÃO VERDE DO BRASIL S.A,2021-11-29,ATIVO,Metalurgia e Siderurgia,PRIVADO,MA,BRASIL,ri@ferroeste.com.br,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
28,08.827.501/0001-58,AEGEA SANEAMENTO E PARTICIPAÇÕES S.A.,AEGEA SANEAMENTO E PARTICIPAÇÕES S.A.,2014-05-21,ATIVO,"Saneamento, Serv. Água e Gás",PRIVADO HOLDING,SP,BRASIL,dri@aegea.com.br,KPMG AUDITORES INDEPENDENTES LTDA.

In [26]:
# Preencher nome comercial vazio com o nome social
df_ativas["DENOM_COMERC"] = df_ativas["DENOM_COMERC"].fillna(df_ativas["DENOM_SOCIAL"])

In [25]:
df_ativas["DENOM_COMERC"] = df_ativas["DENOM_COMERC"].fillna(df_ativas["DENOM_SOCIAL"])
df_ativas["SETOR_ATIV"] = df_ativas["SETOR_ATIV"].fillna("Não informado")

In [24]:
df_ativas = df_limpo[df_limpo["SIT"] == "ATIVO"].copy()