In [4]:
import pandas as pd

print(pd.__version__)

2.3.3

In [9]:
empresas = [
    {"nome": "Petrobras", "setor": "Energia",    "emissoes": 45_800_000, "score_esg": 58},
    {"nome": "Vale",      "setor": "Mineração",  "emissoes": 16_300_000, "score_esg": 72},
    {"nome": "Natura",    "setor": "Consumo",    "emissoes": 890_000,    "score_esg": 91},
    {"nome": "Itaú",      "setor": "Financeiro", "emissoes": 1_200_000,  "score_esg": 85},
    {"nome": "Ambev",     "setor": "Consumo",    "emissoes": 3_400_000,  "score_esg": 63},
]

df = pd.DataFrame(empresas)
df

# Tipos de cada coluna — como DESCRIBE do SQL
df.dtypes

# Resumo estatístico das colunas numéricas
df.describe()

# Primeiras linhas — como SELECT TOP do SQL
df.head(3)

        nome      setor  emissoes  score_esg
0  Petrobras    Energia  45800000         58
1       Vale  Mineração  16300000         72
2     Natura    Consumo    890000         91

In [11]:
# Quantas linhas e colunas
df.shape

(5, 4)

In [12]:
# Tipos de cada coluna — como DESCRIBE do SQL
df.dtypes

nome         object
setor        object
emissoes      int64
score_esg     int64
dtype: object

In [13]:
# Resumo estatístico das colunas numéricas
df.describe()

           emissoes  score_esg
count  5.000000e+00   5.000000
mean   1.351800e+07  73.800000
std    1.912747e+07  14.060583
min    8.900000e+05  58.000000
25%    1.200000e+06  63.000000
50%    3.400000e+06  72.000000
75%    1.630000e+07  85.000000
max    4.580000e+07  91.000000

In [16]:
# Primeiras linhas — como SELECT TOP do SQL
df.head(4)

        nome       setor  emissoes  score_esg
0  Petrobras     Energia  45800000         58
1       Vale   Mineração  16300000         72
2     Natura     Consumo    890000         91
3       Itaú  Financeiro   1200000         85

In [17]:
# Uma coluna — retorna uma Series (como uma lista)
df["nome"]

0    Petrobras
1         Vale
2       Natura
3         Itaú
4        Ambev
Name: nome, dtype: object

In [18]:
df[["nome", "score_esg"]]

        nome  score_esg
0  Petrobras         58
1       Vale         72
2     Natura         91
3       Itaú         85
4      Ambev         63

In [19]:
# Empresas com score acima de 70
df[df["score_esg"] > 70]

     nome       setor  emissoes  score_esg
1    Vale   Mineração  16300000         72
2  Natura     Consumo    890000         91
3    Itaú  Financeiro   1200000         85

In [20]:
# Empresas do setor de Consumo
df[df["setor"] == "Consumo"]

     nome    setor  emissoes  score_esg
2  Natura  Consumo    890000         91
4   Ambev  Consumo   3400000         63

In [21]:
# Combinando filtros — & é o AND, | é o OR
df[(df["score_esg"] > 70) & (df["setor"] == "Consumo")]

     nome    setor  emissoes  score_esg
2  Natura  Consumo    890000         91

In [22]:
# Coluna de classificação — aplicando a lógica da Aula 1
def classificar(score):
    if score >= 80:
        return "Líder"
    elif score >= 60:
        return "Avançado"
    else:
        return "Básico"

df["classificacao"] = df["score_esg"].apply(classificar)
df

        nome       setor  emissoes  score_esg classificacao
0  Petrobras     Energia  45800000         58        Básico
1       Vale   Mineração  16300000         72      Avançado
2     Natura     Consumo    890000         91         Líder
3       Itaú  Financeiro   1200000         85         Líder
4      Ambev     Consumo   3400000         63      Avançado

In [23]:
# Total de emissões por setor
df.groupby("setor")["emissoes"].sum()

setor
Consumo        4290000
Energia       45800000
Financeiro     1200000
Mineração     16300000
Name: emissoes, dtype: int64

In [24]:
# Score médio por setor
df.groupby("setor")["score_esg"].mean()

setor
Consumo       77.0
Energia       58.0
Financeiro    85.0
Mineração     72.0
Name: score_esg, dtype: float64

In [25]:
# Várias agregações de uma vez
df.groupby("setor").agg(
    total_emissoes=("emissoes", "sum"),
    score_medio=("score_esg", "mean"),
    qtd_empresas=("nome", "count")
)

            total_emissoes  score_medio  qtd_empresas
setor
Consumo            4290000         77.0             2
Energia           45800000         58.0             1
Financeiro         1200000         85.0             1
Mineração         16300000         72.0             1

In [29]:
#1 Mostre apenas as colunas nome e score_esg de todas as empresas.

import pandas as pd
empresas = [
    {"nome": "Petrobras", "setor": "Energia",    "emissoes": 45_800_000, "score_esg": 58, "pais": "Brasil"},
    {"nome": "Vale",      "setor": "Mineração",  "emissoes": 16_300_000, "score_esg": 72, "pais": "Brasil"},
    {"nome": "Natura",    "setor": "Consumo",    "emissoes": 890_000,    "score_esg": 91, "pais": "Brasil"},
    {"nome": "Itaú",      "setor": "Financeiro", "emissoes": 1_200_000,  "score_esg": 85, "pais": "Brasil"},
    {"nome": "Ambev",     "setor": "Consumo",    "emissoes": 3_400_000,  "score_esg": 63, "pais": "Brasil"},
    {"nome": "BHP",       "setor": "Mineração",  "emissoes": 41_000_000, "score_esg": 69, "pais": "Austrália"},
    {"nome": "Shell",     "setor": "Energia",    "emissoes": 67_000_000, "score_esg": 55, "pais": "Holanda"},
]

df = pd.DataFrame(empresas)
df[["nome", "score_esg"]]

        nome  score_esg
0  Petrobras         58
1       Vale         72
2     Natura         91
3       Itaú         85
4      Ambev         63
5        BHP         69
6      Shell         55

In [31]:
#2 Filtre e mostre só as empresas com score_esg acima de 65..

import pandas as pd
empresas = [
    {"nome": "Petrobras", "setor": "Energia",    "emissoes": 45_800_000, "score_esg": 58, "pais": "Brasil"},
    {"nome": "Vale",      "setor": "Mineração",  "emissoes": 16_300_000, "score_esg": 72, "pais": "Brasil"},
    {"nome": "Natura",    "setor": "Consumo",    "emissoes": 890_000,    "score_esg": 91, "pais": "Brasil"},
    {"nome": "Itaú",      "setor": "Financeiro", "emissoes": 1_200_000,  "score_esg": 85, "pais": "Brasil"},
    {"nome": "Ambev",     "setor": "Consumo",    "emissoes": 3_400_000,  "score_esg": 63, "pais": "Brasil"},
    {"nome": "BHP",       "setor": "Mineração",  "emissoes": 41_000_000, "score_esg": 69, "pais": "Austrália"},
    {"nome": "Shell",     "setor": "Energia",    "emissoes": 67_000_000, "score_esg": 55, "pais": "Holanda"},
]

df = pd.DataFrame(empresas)
df[(df["score_esg"] > 65)]

     nome       setor  emissoes  score_esg       pais
1    Vale   Mineração  16300000         72     Brasil
2  Natura     Consumo    890000         91     Brasil
3    Itaú  Financeiro   1200000         85     Brasil
5     BHP   Mineração  41000000         69  Austrália

In [32]:
#3 Crie uma coluna nova chamada "emissoes_milhoes" dividindo emissoes por 1.000.000 — fica mais legível.

import pandas as pd
empresas = [
    {"nome": "Petrobras", "setor": "Energia",    "emissoes": 45_800_000, "score_esg": 58, "pais": "Brasil"},
    {"nome": "Vale",      "setor": "Mineração",  "emissoes": 16_300_000, "score_esg": 72, "pais": "Brasil"},
    {"nome": "Natura",    "setor": "Consumo",    "emissoes": 890_000,    "score_esg": 91, "pais": "Brasil"},
    {"nome": "Itaú",      "setor": "Financeiro", "emissoes": 1_200_000,  "score_esg": 85, "pais": "Brasil"},
    {"nome": "Ambev",     "setor": "Consumo",    "emissoes": 3_400_000,  "score_esg": 63, "pais": "Brasil"},
    {"nome": "BHP",       "setor": "Mineração",  "emissoes": 41_000_000, "score_esg": 69, "pais": "Austrália"},
    {"nome": "Shell",     "setor": "Energia",    "emissoes": 67_000_000, "score_esg": 55, "pais": "Holanda"},
]

df = pd.DataFrame(empresas)
df["emissoes_milhoes"] = df["emissoes"] / 1_000_000
df

        nome       setor  emissoes  score_esg       pais  emissoes_milhoes
0  Petrobras     Energia  45800000         58     Brasil             45.80
1       Vale   Mineração  16300000         72     Brasil             16.30
2     Natura     Consumo    890000         91     Brasil              0.89
3       Itaú  Financeiro   1200000         85     Brasil              1.20
4      Ambev     Consumo   3400000         63     Brasil              3.40
5        BHP   Mineração  41000000         69  Austrália             41.00
6      Shell     Energia  67000000         55    Holanda             67.00

In [33]:
#4 Use .groupby() para calcular a média de score_esg por setor.

import pandas as pd
empresas = [
    {"nome": "Petrobras", "setor": "Energia",    "emissoes": 45_800_000, "score_esg": 58, "pais": "Brasil"},
    {"nome": "Vale",      "setor": "Mineração",  "emissoes": 16_300_000, "score_esg": 72, "pais": "Brasil"},
    {"nome": "Natura",    "setor": "Consumo",    "emissoes": 890_000,    "score_esg": 91, "pais": "Brasil"},
    {"nome": "Itaú",      "setor": "Financeiro", "emissoes": 1_200_000,  "score_esg": 85, "pais": "Brasil"},
    {"nome": "Ambev",     "setor": "Consumo",    "emissoes": 3_400_000,  "score_esg": 63, "pais": "Brasil"},
    {"nome": "BHP",       "setor": "Mineração",  "emissoes": 41_000_000, "score_esg": 69, "pais": "Austrália"},
    {"nome": "Shell",     "setor": "Energia",    "emissoes": 67_000_000, "score_esg": 55, "pais": "Holanda"},
]

df = pd.DataFrame(empresas)
df.groupby("setor")["score_esg"].mean()

setor
Consumo       77.0
Energia       56.5
Financeiro    85.0
Mineração     70.5
Name: score_esg, dtype: float64

In [35]:
#5 Encontre a empresa com maior emissão usando .sort_values() — 
# pesquise como usar esse método, é sua primeira vez buscando documentação sozinho!

import pandas as pd
empresas = [
    {"nome": "Petrobras", "setor": "Energia",    "emissoes": 45_800_000, "score_esg": 58, "pais": "Brasil"},
    {"nome": "Vale",      "setor": "Mineração",  "emissoes": 16_300_000, "score_esg": 72, "pais": "Brasil"},
    {"nome": "Natura",    "setor": "Consumo",    "emissoes": 890_000,    "score_esg": 91, "pais": "Brasil"},
    {"nome": "Itaú",      "setor": "Financeiro", "emissoes": 1_200_000,  "score_esg": 85, "pais": "Brasil"},
    {"nome": "Ambev",     "setor": "Consumo",    "emissoes": 3_400_000,  "score_esg": 63, "pais": "Brasil"},
    {"nome": "BHP",       "setor": "Mineração",  "emissoes": 41_000_000, "score_esg": 69, "pais": "Austrália"},
    {"nome": "Shell",     "setor": "Energia",    "emissoes": 67_000_000, "score_esg": 55, "pais": "Holanda"},
]

df = pd.DataFrame(empresas)
df.sort_values(by='emissoes', ascending=False)

        nome       setor  emissoes  score_esg       pais
0  Petrobras     Energia  45800000         58     Brasil
1       Vale   Mineração  16300000         72     Brasil
2     Natura     Consumo    890000         91     Brasil
3       Itaú  Financeiro   1200000         85     Brasil
4      Ambev     Consumo   3400000         63     Brasil
5        BHP   Mineração  41000000         69  Austrália
6      Shell     Energia  67000000         55    Holanda